# Python — List Operations

In [4]:
# Membuat list
data = [10, 20, 'Python', True, 3.14]
# Akses & slicing
print(data[0]) # → 10
print(data[-1]) # → 3.14 (dari belakang)
print(data[1:3]) # → [20, 'Python']
# Manipulasi
data.append(99) # tambah di akhir
data.insert(1, 55) # sisipkan di posisi 1
data.remove(20) # hapus nilai pertama = 20
data.sort() # urutkan (jika tipe sama)

10
3.14
[20, 'Python']


TypeError: '<' not supported between instances of 'str' and 'int'

# Python — Dictionary Operations

In [3]:
mahasiswa = {
'nama': 'Budi Santoso',
'nim': '2024001',
'prodi': 'Informatika',
'ipk': 3.85
}
# Akses nilai
print(mahasiswa['nama']) # → 'Budi Santoso'
print(mahasiswa.get('usia', 0)) # default jika key tak ada
# Update dan hapus
mahasiswa['angkatan'] = 2024 # tambah key baru
del mahasiswa['nim'] # hapus key

Budi Santoso
0


# Python — Membuat NumPy Array

In [5]:
import numpy as np
# Dari list Python
a1D = np.array([1, 2, 3, 4, 5]) # 1D
a2D = np.array([[1,2,3],[4,5,6]]) # 2D
# Array dengan nilai inisial
zeros = np.zeros((3, 4)) # nol semua
ones = np.ones((2, 3)) # satu semua
eye = np.eye(4) # matriks identitas
full = np.full((2, 2), 7) # nilai konstan
# Sequence
arange = np.arange(0, 20, 2) # 0,2,4,...18
linsp = np.linspace(0, 1, 11) # 11 titik merata
# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(100,))

# Python — NumPy Vektorisasi & Statistik

In [6]:
# Operasi aritmetika vektorisasi
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b) # → [11 22 33 44 55]
print(a * b) # → [10 40 90 160 250]
print(a ** 2) # → [1 4 9 16 25]
# Universal functions (ufuncs)
np.sqrt(a) # akar kuadrat tiap elemen
np.exp(a) # eksponensial (e^x)
np.log(b) # logaritma natural
# Fungsi statistik
data = rng.normal(0, 1, 1000)
print(f'Mean: {np.mean(data):.4f}')
print(f'Std: {np.std(data):.4f}')
print(f'Min: {np.min(data):.4f}')
print(f'Max: {np.max(data):.4f}')
print(f'Q1: {np.percentile(data,25):.4f}')
print(f'Q3: {np.percentile(data,75):.4f}')

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
Mean: -0.0163
Std: 1.0008
Min: -3.6484
Max: 3.1789
Q1: -0.6897
Q3: 0.6163


# Python — Pandas Series

In [11]:
import pandas as pd
# Series dari list — index default 0,1,2...
s1 = pd.Series([85, 92, 78, 95, 88])
# Series dengan index kustom
nilai = pd.Series(
[85, 92, 78, 95],
index=['Alice','Bob','Caca','Dina']
)
print(nilai['Bob']) # → 92
print(nilai[nilai>80]) # filter
print(nilai.mean()) # → 87.5
print(nilai.describe()) # statistik lengkap

92
Alice    85
Bob      92
Dina     95
dtype: int64
87.5
count     4.000000
mean     87.500000
std       7.593857
min      78.000000
25%      83.250000
50%      88.500000
75%      92.750000
max      95.000000
dtype: float64


# Python — Membuat Pandas DataFrame

In [9]:
# Membuat DataFrame dari dictionary
data = {
'nama': ['Ali','Budi','Caca','Dina'],
'usia': [22, 25, 21, 23],
'kota': ['Jakarta','Bandung','Surabaya','Medan'],
'ipk': [3.8, 3.5, 3.9, 3.7]
}
df = pd.DataFrame(data)
# Informasi dasar
print(df.shape) # → (4, 4)
print(df.dtypes) # tipe data per kolom
print(df.columns) # nama-nama kolom

(4, 4)
nama     object
usia      int64
kota     object
ipk     float64
dtype: object
Index(['nama', 'usia', 'kota', 'ipk'], dtype='object')


# Hands on — pd.read_csv()

In [25]:
import pandas as pd

# Memuat dari URL (dataset publik)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


# Q1 - Berapa jumlah baris dan kolom pada dataset Titanic? Kolom apa saja yang tersedia?

In [24]:
print("Shape (baris, kolom): ", df.shape) # mengambil jumlah baris dan kolom pada data csv yang dimuat
print("List Kolom: ", df.columns.tolist()) # mengambil daftar kolom yang terdapat pada data csv yang dimuat

Shape (baris, kolom):  (891, 12)
List Kolom:  ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']


# Q2 - Kolom mana saja yang memiliki missing values? Berapa jumlah dan proporsinya (%) per kolom?

In [31]:
missing = df.isnull().sum() # mengambil kolom mana saja yang memiliki field yang kosong diantara semua baris data
percent = (df.isnull().sum() / len(df)) * 100 # menjumlahkan lalu membuat rata-rata dari total data yang kosong dengan jumlah keseluruhan data

missing_df = pd.DataFrame({
    'Jumlah field kosong': missing,
    'Persentase (%)': percent.round(2)
})

print(missing_df[missing_df['Jumlah field kosong'] > 0])

          Jumlah field kosong  Persentase (%)
Age                       177           19.87
Cabin                     687           77.10
Embarked                    2            0.22


# Q3 - Berapa persen penumpang yang selamat (Survived=1)? Gunakan operasi NumPy atau Pandas.

In [44]:
survived_pct = df['Survived'].mean() * 100 # mengambil persentase dari semua penumpang yang selamat
print(f"Persentase penumpang yang selamat: {survived_pct.round(2)}%")

Persentase penumpang yang selamat: 38.38%


# Q4 - Filter penumpang wanita dari kelas 1 (Pclass=1). Berapa jumlahnya dan berapa rata-rata usianya?

In [43]:
female_c1 = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)] # mengambil data dengan gender "female" dan pclass "1"
total_female_c1 = len(female_c1) # mengambil jumlah semua data dari data di atas
avg_age_female_c1 = female_c1['Age'].mean() # mengambil rata-rata usia dari keseluruhan data di atas

print(f"Analisis Wanita Kelas 1")
print(f"- Jumlah Penumpang: {total_female_c1}")
print(f"- Rata-rata Usia  : {avg_age_female_c1.round()} tahun")

Analisis Wanita Kelas 1
- Jumlah Penumpang: 94
- Rata-rata Usia  : 35.0 tahun


# Q5 - Gunakan groupby untuk menghitung tingkat keselamatan (mean Survived) per kelas penumpang. Kelas mana yang paling tinggi?

In [39]:
print("Tingkat keselamatan per kelas penumpang")
survived_by_class = df.groupby('Pclass')['Survived'].mean() * 100 # mengambil rata-rata penumpang selamat per kelas penumpang
print(survived_by_class)
print(f"Kelas dengan tingkat keselamatan tertinggi yaitu: Kelas {survived_by_class.idxmax()}")

Tingkat keselamatan per kelas penumpang
Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64
Kelas dengan tingkat keselamatan tertinggi yaitu: Kelas 1


# Q6 - Buat analisis tambahan berdasarkan variabel lain yang Anda anggap menarik. Sertakan interpretasi singkat.

In [62]:
result = df.groupby('Sex').agg(
  jumlah = ('PassengerId', 'count'),
  selamat = ('Survived', 'sum'),
  rata_usia = ('Age', 'mean'),
)
result = result.round()
print(result)
print("Dari data tersebut, jumlah penumpang wanita lebih sedikit daripada jumlah penumpang laki-laki, namun penumpang wanita memiliki jumlah korban selamat lebih banyak daripada laki-laki.")

        jumlah  selamat  rata_usia
Sex                               
female     314      233       28.0
male       577      109       31.0
Dari data tersebut, jumlah penumpang wanita lebih sedikit daripada jumlah penumpang laki-laki, namun penumpang wanita memiliki jumlah korban selamat lebih banyak daripada laki-laki.
